version: "3"

# port for this project used: 1024 ~ 1099

services:
  # Databases
  mysql:
    image: ${MYSQL_SERVICE}:${MYSQL_VERSION}
    container_name: ${MYSQL_SERVICE}
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - ${MYSQL_PORT}:${MYSQL_INTERNAL_PORT}
    volumes:
      - ${MYSQL_CONFIG}:/etc/mysql/conf.d/my.conf
      - ${MYSQL_DATA_DIR}:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
  mariadb:
    image: ${MARIADB_SERVICE}:${MARIADB_VERSION}
    container_name: ${MARIADB_SERVICE}
    restart: always
    ports:
      - ${MARIADB_PORT}:${MARIADB_INTERNAL_PORT}
    volumes:
      - ${MARIADB_CONFIG}:/etc/mysql/conf.d/my.conf
      - ${MARIADB_DATA_DIR}:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
  mssql:
    image: mcr.microsoft.com/mssql/server:${MSSQL_VERSION}
    container_name: ${MSSQL_SERVICE}
    restart: always
    ports:
      - ${MSSQL_PORT}:${MSSQL_INTERNEL_PORT}
    environment:
      ACCEPT_EULA: ${MSSQL_ACCEPT_EULA}
      SA_PASSWORD: ${MSSQL_SA_PASSWORD}
  postgres:
    image: ${POSTGRES_SERVICE}:${POSTGRES_VERSION}
    container_name: ${POSTGRES_SERVICE}
    restart: always
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_INTERNEL_PORT}
    volumes:
      - ${POSTGRES_DATA_DIR}:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_ROOT_PASSWORD}
  mongo:
    image: mongo:${MONGO_VERSION}
    container_name: ${MONGO_SERVICE}
    restart: always
    ports:
      - ${MONGO_PORT}:${MONGO_INTERNEL_PORT}
    volumes:
      - ${MONGO_DATA_DIR}:/data/db
      - ${MONGO_CONFIG}:/etc/mongod.conf
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
  redis:
    image: ${REDIS_SERVICE}:${REDIS_VERSION}
    container_name: ${REDIS_SERVICE}
    restart: always
    command: --requirepass ${REDIS_ROOT_PASSWORD}
    ports:
      - ${REDIS_PORT}:${REDIS_INTERNEL_PORT}
    volumes:
      - ${REDIS_DATA_DIR}:/data

  # Programming Language Base
  node:
    image: ${NODE_SERVICE}:${NODE_VERSION}
    container_name: ${NODE_SERVICE}
  python:
    image: ${PYTHON_SERVICE}:${PYTHON_VERSION}
    container_name: ${PYTHON_SERVICE}
  openjdk:
    image: ${OPENJDK_SERVICE}:${OPENJDK_VERSION}
    container_name: ${OPENJDK_SERVICE}

  # Web Container
  nginx:
    image: ${NGINX_SERVICE}:${NGINX_VERSION}
    container_name: ${NGINX_SERVICE}
    restart: always
    ports:
      - ${NGINX_PORT}:${NGINX_INTERNAL_PORT}
    # volumes:
    #   - ${NGINX_DATA_DIR}:/usr/share/nginx/html
    #   - ${NGINX_CONFIG_DIR}:/etc/nginx/conf.d/
  tomcat:
    image: ${TOMCAT_SERVICE}:${TOMCAT_VERSION}
    container_name: ${TOMCAT_SERVICE}
    restart: always
    ports:
      - ${TOMCAT_PORT}:${TOMCAT_INTERNAL_PORT}
    volumes:
      - ${TOMCAT_WEBAPPS_DIR}:/usr/local/tomcat/webapps
      - ${TOMCAT_CONFIG_DIR}:/usr/local/tomcat/conf
  # wordpress
  # Other Tools
  # registry:
  # sonarqube
  # jenkins
  # redmine
